version: "3.9"

services:
  app:
    container_name: todos_app
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app/api
    ports:
      - 8080:8080
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    container_name: db_postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
    ports:
      - '5432:5432'
      
volumes:
  data: